project:
  type: website
output-dir: docs

website:
  title: "Marianellie Bravo's CV"
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Education & Experience"
        href: education.qmd
      - text: "Code & Files"
        href: Code.qmd

format:
  html:
    theme: morph
    toc: true
    css: styles.css